server:
  port: 8888

spring:
  main:
    banner-mode: off
  application:
    name: membership
  datasource:
    url: jdbc:h2:file:./data/membership;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2/console
  sql:
    init:
      mode: always

